VIA_ENABLE = yes
VIAL_ENABLE = yes

VIAL_INSECURE = yes
VIALRGB_ENABLE = yes
VIAL_ENCODERS_ENABLE = yes

#define VIAL_UNLOCK_ROWS { 1,3 }
#define VIAL_UNLOCK_COLS { 10,4 }

COMBO_ENABLE = no
MOUSEKEY_ENABLE = no
KEY_OVERRIDE_ENABLE = yes
AUTO_SHIFT_ENABLE = yes
TAP_DANCE_ENABLE = yes